import { useRef, useState, type CSSProperties, type PointerEvent, type ReactElement } from 'react';
import type { Translator } from '../i18n';
import { activeCharacterNames, characterPosition, getBeatPlace, isCharacterActive, mapPlaces, normalizeName, placeLabel } from '../mapData';
import type { CharacterRecord, Language, StoryBeat, WorldSummary } from '../types';

type Props = {
  language: Language;
  world: WorldSummary | null;
  characters: CharacterRecord[];
  beat: StoryBeat | null;
  t: Translator;
};

const townDecor = [
  { type: 'tree', x: 9, y: 17 },
  { type: 'tree', x: 14, y: 21 },
  { type: 'tree', x: 9, y: 69 },
  { type: 'tree', x: 16, y: 80 },
  { type: 'tree', x: 87, y: 15 },
  { type: 'tree', x: 91, y: 25 },
  { type: 'tree', x: 85, y: 67 },
  { type: 'flower', x: 30, y: 84 },
  { type: 'flower', x: 23, y: 82 },
  { type: 'flower', x: 58, y: 71 },
  { type: 'rock', x: 33, y: 17 },
  { type: 'rock', x: 67, y: 18 },
  { type: 'rock', x: 83, y: 56 },
];

export function TownMap({ language, world, characters, beat }: Props): ReactElement {
  const activePlace = getBeatPlace(beat);
  const period = (beat?.timeSlot ?? 'day').toLowerCase().replace(/\s+/g, '-');
  const [pan, setPan] = useState({ x: -14, y: -12 });
  const dragRef = useRef<{ id: number; startX: number; startY: number; panX: number; panY: number } | null>(null);

  const beginDrag = (event: PointerEvent<HTMLDivElement>): void => {
    event.currentTarget.setPointerCapture(event.pointerId);
    dragRef.current = { id: event.pointerId, startX: event.clientX, startY: event.clientY, panX: pan.x, panY: pan.y };
  };

  const dragMap = (event: PointerEvent<HTMLDivElement>): void => {
    const drag = dragRef.current;
    if (!drag || drag.id !== event.pointerId) return;
    setPan({
      x: clampPan(drag.panX + event.clientX - drag.startX),
      y: clampPan(drag.panY + event.clientY - drag.startY),
    });
  };

  const endDrag = (event: PointerEvent<HTMLDivElement>): void => {
    if (dragRef.current?.id === event.pointerId) dragRef.current = null;
  };

  return (
    <div
      className="town-viewport"
      onPointerDown={beginDrag}
      onPointerMove={dragMap}
      onPointerUp={endDrag}
      onPointerCancel={endDrag}
      role="application"
      aria-label="Draggable town map"
    >
      <div className="town-drag-layer" style={{ '--pan-x': `${pan.x}px`, '--pan-y': `${pan.y}px` } as CSSProperties}>
        <div className="town-scene ai-town-scene" data-period={period}>
          <div className="tile-layer grass-layer" />
          <div className="map-water river-band" />
          <div className="map-road main-road" />
          <div className="map-road cross-road" />
          <div className="map-road market-road" />
          <div className="plaza town-square-tile" />
          {townDecor.map((item, index) => (
            <span
              className={`town-decor decor-${item.type}`}
              style={{ '--x': `${item.x}%`, '--y': `${item.y}%` } as CSSProperties}
              key={`${item.type}-${index}`}
            />
          ))}
          {mapPlaces.map((place) => (
            <div
              className={`map-place place-${place.key} ${place.key === activePlace.key ? 'active' : ''}`}
              style={{ '--x': `${place.x}%`, '--y': `${place.y}%` } as CSSProperties}
              key={place.key}
            >
              <span className="place-building" />
              <strong>{placeLabel(place, language)}</strong>
            </div>
          ))}
          <TownCharacters world={world} characters={characters} beat={beat} activePlace={activePlace} />
          <div className="map-light" />
        </div>
      </div>
    </div>
  );
}

export function MapFocus({ language, beat, t }: { language: Language; beat: StoryBeat | null; t: Translator }): ReactElement {
  if (!beat) return <p className="map-focus">{t('quietTown')}</p>;
  const place = getBeatPlace(beat);
  const activeNames = activeCharacterNames(beat);
  return (
    <div className="map-focus">
      <div className="map-focus-title">
        <strong>
          {t('mapFocus')}: {beat.timeSlot} · {placeLabel(place, language)}
        </strong>
        {beat.location !== place.label ? <span>{beat.location}</span> : null}
      </div>
      <p>{activeNames.length > 0 ? `${t('activeResidents')}: ${activeNames.join(', ')}` : t('quietTown')}</p>
    </div>
  );
}

function TownCharacters({
  world,
  characters,
  beat,
  activePlace,
}: {
  world: WorldSummary | null;
  characters: CharacterRecord[];
  beat: StoryBeat | null;
  activePlace: ReturnType<typeof getBeatPlace>;
}): ReactElement {
  const rendered =
    characters.length > 0
      ? characters
      : Array.from({ length: Math.max(world?.characterCount ?? 3, 3) }).map((_, index) => ({
          id: `placeholder-${index}`,
          name: String(index + 1),
          gender: '',
          personality: '',
          appearance: '',
          backstory: '',
          isAutoGenerated: false,
        }));
  const activeNames = new Set(activeCharacterNames(beat).map(normalizeName));
  const hasMatchedActive = characters.some((character) => isCharacterActive(character.name, activeNames));
  const colors = ['#d84f45', '#3b72b9', '#3f9f5f', '#8d61c4', '#c9812a', '#2d9290', '#c85d88', '#5d6874'];
  const hairColors = ['#23332a', '#5f4634', '#e3d3a0', '#26364f', '#6c352a', '#2d5141', '#432e63', '#3f4147'];

  return (
    <>
      {rendered.slice(0, 12).map((character, index) => {
        const active = isCharacterActive(character.name, activeNames) || (!hasMatchedActive && Boolean(beat) && index < 2);
        const position = characterPosition(index, rendered.length, active, activePlace, beat?.timeSlot ?? '');
        return (
          <div
            className={`character pixel-character ${active ? 'active' : ''}`}
            style={
              {
                '--x': `${position.x}%`,
                '--y': `${position.y}%`,
                '--color': colors[index % colors.length],
                '--hair': hairColors[index % hairColors.length],
              } as CSSProperties
            }
            title={character.name}
            key={character.id}
          >
            <span className="sprite-shadow" />
            <span className="sprite-head">
              <span className="sprite-hair" />
              <span className="sprite-eye eye-left" />
              <span className="sprite-eye eye-right" />
            </span>
            <span className="sprite-body">
              <span className="sprite-leg leg-left" />
              <span className="sprite-leg leg-right" />
            </span>
            <small>{character.name}</small>
          </div>
        );
      })}
    </>
  );
}

function clampPan(value: number): number {
  return Math.min(0, Math.max(-220, value));
}
