import type { CSSProperties, ReactElement } from 'react';
import type { Translator } from '../i18n';
import { activeCharacterNames, characterPosition, getBeatPlace, isCharacterActive, mapPlaces, normalizeName, placeLabel } from '../mapData';
import type { CharacterRecord, Language, StoryBeat, WorldSummary } from '../types';

type Props = {
  language: Language;
  world: WorldSummary | null;
  characters: CharacterRecord[];
  beat: StoryBeat | null;
  t: Translator;
};

export function TownMap({ language, world, characters, beat, t }: Props): ReactElement {
  const activePlace = getBeatPlace(beat);
  const period = (beat?.timeSlot ?? 'day').toLowerCase().replace(/\s+/g, '-');

  return (
    <div className="town-scene" data-period={period}>
      <div className="map-road main-road" />
      <div className="map-road cross-road" />
      <div className="map-water" />
      <div className="plaza" />
      {mapPlaces.map((place) => (
        <div
          className={`map-place ${place.key === activePlace.key ? 'active' : ''}`}
          style={{ '--x': `${place.x}%`, '--y': `${place.y}%` } as CSSProperties}
          key={place.key}
        >
          <span />
          <strong>{placeLabel(place, language)}</strong>
        </div>
      ))}
      <TownCharacters world={world} characters={characters} beat={beat} activePlace={activePlace} />
    </div>
  );
}

export function MapFocus({ language, beat, t }: { language: Language; beat: StoryBeat | null; t: Translator }): ReactElement {
  if (!beat) return <p className="map-focus">{t('quietTown')}</p>;
  const place = getBeatPlace(beat);
  const activeNames = activeCharacterNames(beat);
  return (
    <div className="map-focus">
      <div className="map-focus-title">
        <strong>
          {t('mapFocus')}: {beat.timeSlot} · {placeLabel(place, language)}
        </strong>
        {beat.location !== place.label ? <span>{beat.location}</span> : null}
      </div>
      <p>{activeNames.length > 0 ? `${t('activeResidents')}: ${activeNames.join(', ')}` : t('quietTown')}</p>
    </div>
  );
}

function TownCharacters({
  world,
  characters,
  beat,
  activePlace,
}: {
  world: WorldSummary | null;
  characters: CharacterRecord[];
  beat: StoryBeat | null;
  activePlace: ReturnType<typeof getBeatPlace>;
}): ReactElement {
  const rendered =
    characters.length > 0
      ? characters
      : Array.from({ length: Math.max(world?.characterCount ?? 3, 3) }).map((_, index) => ({
          id: `placeholder-${index}`,
          name: String(index + 1),
          gender: '',
          personality: '',
          appearance: '',
          backstory: '',
          isAutoGenerated: false,
        }));
  const activeNames = new Set(activeCharacterNames(beat).map(normalizeName));
  const hasMatchedActive = characters.some((character) => isCharacterActive(character.name, activeNames));
  const colors = ['#f66f5e', '#3d8bfd', '#28a96f', '#a26be8', '#d28b19', '#0f9f9a', '#cf5f98', '#697386'];

  return (
    <>
      {rendered.slice(0, 12).map((character, index) => {
        const active = isCharacterActive(character.name, activeNames) || (!hasMatchedActive && Boolean(beat) && index < 2);
        const position = characterPosition(index, rendered.length, active, activePlace, beat?.timeSlot ?? '');
        return (
          <div
            className={`character ${active ? 'active' : ''}`}
            style={{ '--x': `${position.x}%`, '--y': `${position.y}%`, '--color': colors[index % colors.length] } as CSSProperties}
            title={character.name}
            key={character.id}
          >
            <span>{character.name.slice(0, 1) || String(index + 1)}</span>
            <small>{character.name}</small>
          </div>
        );
      })}
    </>
  );
}
