import { newId } from './crypto';
import type { AuthContext, Env } from './types';

export interface CharacterRecord {
  id: string;
  name: string;
  gender: string;
  personality: string;
  appearance: string;
  backstory: string;
  isAutoGenerated: boolean;
}

export interface LexiconRecord {
  id: string;
  term: string;
  description: string;
  language: 'en' | 'zh' | 'both';
}

export interface StoryRecord {
  dayNumber: number;
  title: string;
  content: string;
  language: 'en' | 'zh';
  model: string;
  createdAt: string;
  beats: StoryBeatRecord[];
}

export interface StoryBeatRecord {
  beatIndex: number;
  timeSlot: string;
  location: string;
  mood: string;
  event: string;
  dialogue: string[];
  participatingCharacters: string[];
  memoryImpact: string;
}

export interface WorldContent {
  characters: CharacterRecord[];
  lexiconEntries: LexiconRecord[];
  stories: StoryRecord[];
}

interface CharacterRow {
  id: string;
  name: string;
  gender: string;
  personality: string;
  appearance: string;
  backstory: string;
  is_auto_generated: number;
}

interface LexiconRow {
  id: string;
  term: string;
  description: string;
  language: 'en' | 'zh' | 'both';
}

interface StoryRow {
  id: string;
  day_number: number;
  title: string;
  content: string;
  language: 'en' | 'zh';
  model: string;
  created_at: string;
}

interface BeatRow {
  story_id: string;
  beat_index: number;
  time_slot: string;
  location: string;
  mood: string;
  event: string;
  dialogue: string;
  participating_characters: string;
  memory_impact: string;
}

export async function getWorldContent(env: Env, auth: AuthContext, worldId: string): Promise<WorldContent | null> {
  if (!(await ownsWorld(env, auth, worldId))) return null;

  const [characters, lexiconEntries, stories, beats] = await Promise.all([
    env.DB.prepare(
      `SELECT id, name, gender, personality, appearance, backstory, is_auto_generated
       FROM characters
       WHERE world_id = ? AND user_id = ?
       ORDER BY created_at ASC`,
    )
      .bind(worldId, auth.user.id)
      .all<CharacterRow>(),
    env.DB.prepare(
      `SELECT id, term, description, language
       FROM lexicon_entries
       WHERE world_id = ? AND user_id = ?
       ORDER BY created_at ASC`,
    )
      .bind(worldId, auth.user.id)
      .all<LexiconRow>(),
    env.DB.prepare(
      `SELECT id, day_number, title, content, language, model, created_at
       FROM stories
       WHERE world_id = ? AND user_id = ?
       ORDER BY day_number DESC
       LIMIT 20`,
    )
      .bind(worldId, auth.user.id)
      .all<StoryRow>(),
    env.DB.prepare(
      `SELECT story_id, beat_index, time_slot, location, mood, event, dialogue, participating_characters, memory_impact
       FROM story_beats
       WHERE world_id = ? AND user_id = ?
       ORDER BY beat_index ASC`,
    )
      .bind(worldId, auth.user.id)
      .all<BeatRow>(),
  ]);
  const beatsByStory = groupBeats(beats.results);

  return {
    characters: characters.results.map(toCharacter),
    lexiconEntries: lexiconEntries.results,
    stories: stories.results.map((story) => ({
      dayNumber: story.day_number,
      title: story.title,
      content: story.content,
      language: story.language,
      model: story.model,
      createdAt: story.created_at,
      beats: beatsByStory.get(story.id) ?? [],
    })),
  };
}

export async function createCharacter(
  env: Env,
  auth: AuthContext,
  worldId: string,
  input: Partial<CharacterRecord>,
): Promise<CharacterRecord | null> {
  if (!(await ownsWorld(env, auth, worldId))) return null;

  const character = normalizeCharacter(input);
  const id = newId('chr');
  await env.DB.batch([
    env.DB.prepare(
      `INSERT INTO characters
        (id, world_id, user_id, name, gender, personality, appearance, backstory, is_auto_generated)
       VALUES (?, ?, ?, ?, ?, ?, ?, ?, 0)`,
    ).bind(
      id,
      worldId,
      auth.user.id,
      character.name,
      character.gender,
      character.personality,
      character.appearance,
      character.backstory,
    ),
    touchWorld(env, auth.user.id, worldId),
  ]);
  return { ...character, id, isAutoGenerated: false };
}

export async function updateCharacter(
  env: Env,
  auth: AuthContext,
  worldId: string,
  characterId: string,
  input: Partial<CharacterRecord>,
): Promise<CharacterRecord | null> {
  if (!(await ownsWorld(env, auth, worldId))) return null;

  const existing = await env.DB.prepare(
    `SELECT id, name, gender, personality, appearance, backstory, is_auto_generated
     FROM characters
     WHERE id = ? AND world_id = ? AND user_id = ?
     LIMIT 1`,
  )
    .bind(characterId, worldId, auth.user.id)
    .first<CharacterRow>();
  if (!existing) return null;

  const character = normalizeCharacter({
    id: existing.id,
    name: input.name ?? existing.name,
    gender: input.gender ?? existing.gender,
    personality: input.personality ?? existing.personality,
    appearance: input.appearance ?? existing.appearance,
    backstory: input.backstory ?? existing.backstory,
    isAutoGenerated: existing.is_auto_generated === 1,
  });

  await env.DB.batch([
    env.DB.prepare(
      `UPDATE characters
       SET name = ?, gender = ?, personality = ?, appearance = ?, backstory = ?, updated_at = datetime('now')
       WHERE id = ? AND world_id = ? AND user_id = ?`,
    ).bind(
      character.name,
      character.gender,
      character.personality,
      character.appearance,
      character.backstory,
      characterId,
      worldId,
      auth.user.id,
    ),
    touchWorld(env, auth.user.id, worldId),
  ]);

  return {
    ...character,
    id: characterId,
    isAutoGenerated: existing.is_auto_generated === 1,
  };
}

export async function deleteCharacter(
  env: Env,
  auth: AuthContext,
  worldId: string,
  characterId: string,
): Promise<boolean> {
  if (!(await ownsWorld(env, auth, worldId))) return false;
  const result = await env.DB.batch([
    env.DB.prepare(`DELETE FROM characters WHERE id = ? AND world_id = ? AND user_id = ?`).bind(
      characterId,
      worldId,
      auth.user.id,
    ),
    touchWorld(env, auth.user.id, worldId),
  ]);
  return (result[0]?.meta.changes ?? 0) > 0;
}

export async function createLexiconEntry(
  env: Env,
  auth: AuthContext,
  worldId: string,
  input: Partial<LexiconRecord>,
): Promise<LexiconRecord | null> {
  if (!(await ownsWorld(env, auth, worldId))) return null;
  const entry = normalizeLexicon(input);
  const id = newId('lex');
  await env.DB.batch([
    env.DB.prepare(
      `INSERT INTO lexicon_entries (id, world_id, user_id, term, description, language)
       VALUES (?, ?, ?, ?, ?, ?)`,
    ).bind(id, worldId, auth.user.id, entry.term, entry.description, entry.language),
    touchWorld(env, auth.user.id, worldId),
  ]);
  return { ...entry, id };
}

export async function deleteLexiconEntry(
  env: Env,
  auth: AuthContext,
  worldId: string,
  lexiconId: string,
): Promise<boolean> {
  if (!(await ownsWorld(env, auth, worldId))) return false;
  const result = await env.DB.batch([
    env.DB.prepare(`DELETE FROM lexicon_entries WHERE id = ? AND world_id = ? AND user_id = ?`).bind(
      lexiconId,
      worldId,
      auth.user.id,
    ),
    touchWorld(env, auth.user.id, worldId),
  ]);
  return (result[0]?.meta.changes ?? 0) > 0;
}

async function ownsWorld(env: Env, auth: AuthContext, worldId: string): Promise<boolean> {
  const row = await env.DB.prepare(`SELECT id FROM worlds WHERE id = ? AND user_id = ? LIMIT 1`)
    .bind(worldId, auth.user.id)
    .first<{ id: string }>();
  return row !== null;
}

function touchWorld(env: Env, userId: string, worldId: string): D1PreparedStatement {
  return env.DB.prepare(`UPDATE worlds SET updated_at = datetime('now') WHERE id = ? AND user_id = ?`).bind(
    worldId,
    userId,
  );
}

function normalizeCharacter(input: Partial<CharacterRecord>): Omit<CharacterRecord, 'id' | 'isAutoGenerated'> {
  return {
    name: clampText(input.name, 'New Character', 60),
    gender: clampText(input.gender, 'unspecified', 40),
    personality: clampText(input.personality, 'Curious and open to unexpected conversations.', 500),
    appearance: clampText(input.appearance, 'A memorable town resident with a distinct silhouette.', 500),
    backstory: clampText(input.backstory, '', 1000),
  };
}

function normalizeLexicon(input: Partial<LexiconRecord>): Omit<LexiconRecord, 'id'> {
  const language = input.language === 'zh' || input.language === 'both' ? input.language : 'en';
  return {
    term: clampText(input.term, 'New term', 80),
    description: clampText(input.description, '', 600),
    language,
  };
}

function clampText(value: string | undefined, fallback: string, maxLength: number): string {
  const trimmed = (value ?? '').trim();
  return (trimmed || fallback).slice(0, maxLength);
}

function toCharacter(row: CharacterRow): CharacterRecord {
  return {
    id: row.id,
    name: row.name,
    gender: row.gender,
    personality: row.personality,
    appearance: row.appearance,
    backstory: row.backstory,
    isAutoGenerated: row.is_auto_generated === 1,
  };
}

function groupBeats(rows: BeatRow[]): Map<string, StoryBeatRecord[]> {
  const grouped = new Map<string, StoryBeatRecord[]>();
  for (const row of rows) {
    const list = grouped.get(row.story_id) ?? [];
    list.push({
      beatIndex: row.beat_index,
      timeSlot: row.time_slot,
      location: row.location,
      mood: row.mood,
      event: row.event,
      dialogue: parseJsonList(row.dialogue),
      participatingCharacters: parseJsonList(row.participating_characters),
      memoryImpact: row.memory_impact,
    });
    grouped.set(row.story_id, list);
  }
  return grouped;
}

function parseJsonList(value: string): string[] {
  try {
    const parsed = JSON.parse(value) as unknown;
    return Array.isArray(parsed) ? parsed.filter((item): item is string => typeof item === 'string') : [];
  } catch {
    return [];
  }
}
