import { newId } from './crypto';
import type { AuthContext, Env, WorldSummary } from './types';

type Language = 'en' | 'zh';

interface WorldRow {
  id: string;
  name: string;
  language: Language;
  story_day: number;
  created_at: string;
  updated_at: string;
  auto_advance_enabled: number;
  character_count: number;
  memory_count: number;
  story_count: number;
}

export interface WorldExportData {
  format: 'ai-town-lite-world';
  version: 1;
  exportedAt: string;
  source: {
    worldName: string;
    storyDay: number;
    language: Language;
  };
  world: {
    name: string;
    language: Language;
    storyDay: number;
  };
  characters: Array<{
    id: string;
    name: string;
    gender: string;
    personality: string;
    appearance: string;
    backstory: string;
    isAutoGenerated: boolean;
  }>;
  memories: Array<{
    id: string;
    characterId: string | null;
    content: string;
    source: string;
    importance: number;
  }>;
  lexiconEntries: Array<{
    id: string;
    term: string;
    description: string;
    language: 'en' | 'zh' | 'both';
  }>;
  stories: Array<{
    id?: string;
    dayNumber: number;
    title: string;
    content: string;
    language: Language;
    model: string;
    promptHash: string;
    beats?: Array<{
      beatIndex: number;
      timeSlot: string;
      location: string;
      mood: string;
      event: string;
      dialogue: string[];
      participatingCharacters: string[];
      memoryImpact: string;
    }>;
  }>;
}

const defaultCharacters = [
  {
    name: 'Mira',
    gender: 'female',
    personality: 'Curious, careful, and fond of collecting old town rumors.',
    appearance: 'Short silver hair, amber scarf, and a satchel full of notes.',
    backstory: 'Mira keeps the town archive and believes every tiny event is part of a larger pattern.',
  },
  {
    name: 'Jun',
    gender: 'male',
    personality: 'Inventive, optimistic, and easily distracted by impossible machines.',
    appearance: 'Round glasses, blue jacket, ink-stained fingers.',
    backstory: 'Jun repairs broken devices and dreams of building a clock that predicts tomorrow.',
  },
  {
    name: 'Rose',
    gender: 'nonbinary',
    personality: 'Warm, practical, and quietly stubborn when protecting friends.',
    appearance: 'Green coat, braided hair, and boots covered in garden soil.',
    backstory: 'Rose tends the central garden and notices emotional weather before anyone else.',
  },
] as const;

const defaultMemories = [
  'Mira once found a sealed letter hidden under the town fountain.',
  'Jun believes the old clocktower ticks faster when someone tells a lie.',
  'Rose planted moonflowers that open only after important conversations.',
  'The town square smells like rain even on clear mornings.',
  'A missing map shows tunnels below the bakery.',
  'Mira promised to catalogue every strange event for one full year.',
  'Jun built a tiny brass bird that repeats overheard secrets.',
  'Rose distrusts anyone who steps on the herb beds.',
  'The three friends meet at sunset whenever the bell rings twice.',
  'Nobody knows who leaves blue candles on the bridge.',
] as const;

export async function createDefaultWorld(
  env: Env,
  userId: string,
  options: { name?: string; language?: Language } = {},
): Promise<string> {
  const worldId = newId('wld');
  const language = options.language ?? 'en';
  const name = sanitizeName(options.name ?? 'AI Town Lite');

  const statements = [
    env.DB.prepare(
      `INSERT INTO worlds (id, user_id, name, language, story_day)
       VALUES (?, ?, ?, ?, ?)`,
    ).bind(worldId, userId, name, language, 1),
  ];

  const characterIds = defaultCharacters.map(() => newId('chr'));
  for (let i = 0; i < defaultCharacters.length; i += 1) {
    const character = defaultCharacters[i]!;
    statements.push(
      env.DB.prepare(
        `INSERT INTO characters
          (id, world_id, user_id, name, gender, personality, appearance, backstory, is_auto_generated)
         VALUES (?, ?, ?, ?, ?, ?, ?, ?, 0)`,
      ).bind(
        characterIds[i]!,
        worldId,
        userId,
        character.name,
        character.gender,
        character.personality,
        character.appearance,
        character.backstory,
      ),
    );
  }

  for (let i = 0; i < defaultMemories.length; i += 1) {
    statements.push(
      env.DB.prepare(
        `INSERT INTO memories (id, world_id, user_id, character_id, content, source, importance)
         VALUES (?, ?, ?, ?, ?, ?, ?)`,
      ).bind(newId('mem'), worldId, userId, characterIds[i % characterIds.length]!, defaultMemories[i]!, 'seed', 3),
    );
  }

  await env.DB.batch(statements);
  return worldId;
}

export async function listWorlds(env: Env, auth: AuthContext): Promise<WorldSummary[]> {
  const rows = await env.DB.prepare(
    `SELECT
       worlds.id,
       worlds.name,
       worlds.language,
       worlds.story_day,
       worlds.created_at,
       worlds.updated_at,
       worlds.auto_advance_enabled,
       COUNT(DISTINCT characters.id) AS character_count,
       COUNT(DISTINCT memories.id) AS memory_count,
       COUNT(DISTINCT stories.id) AS story_count
     FROM worlds
     LEFT JOIN characters ON characters.world_id = worlds.id AND characters.user_id = worlds.user_id
     LEFT JOIN memories ON memories.world_id = worlds.id AND memories.user_id = worlds.user_id
     LEFT JOIN stories ON stories.world_id = worlds.id AND stories.user_id = worlds.user_id
     WHERE worlds.user_id = ?
     GROUP BY worlds.id
     ORDER BY worlds.updated_at DESC`,
  )
    .bind(auth.user.id)
    .all<WorldRow>();

  return rows.results.map(toWorldSummary);
}

export async function getWorldSnapshot(env: Env, auth: AuthContext, worldId: string): Promise<WorldExportData | null> {
  const world = await env.DB.prepare(
    `SELECT id, name, language, story_day
     FROM worlds
     WHERE id = ? AND user_id = ?
     LIMIT 1`,
  )
    .bind(worldId, auth.user.id)
    .first<{ id: string; name: string; language: Language; story_day: number }>();

  if (!world) return null;

  const [characters, memories, lexiconEntries, stories, beats] = await Promise.all([
    env.DB.prepare(
      `SELECT id, name, gender, personality, appearance, backstory, is_auto_generated
       FROM characters
       WHERE world_id = ? AND user_id = ?
       ORDER BY created_at ASC`,
    )
      .bind(worldId, auth.user.id)
      .all<{
        id: string;
        name: string;
        gender: string;
        personality: string;
        appearance: string;
        backstory: string;
        is_auto_generated: number;
      }>(),
    env.DB.prepare(
      `SELECT id, character_id, content, source, importance
       FROM memories
       WHERE world_id = ? AND user_id = ?
       ORDER BY created_at ASC`,
    )
      .bind(worldId, auth.user.id)
      .all<{ id: string; character_id: string | null; content: string; source: string; importance: number }>(),
    env.DB.prepare(
      `SELECT id, term, description, language
       FROM lexicon_entries
       WHERE world_id = ? AND user_id = ?
       ORDER BY created_at ASC`,
    )
      .bind(worldId, auth.user.id)
      .all<{ id: string; term: string; description: string; language: 'en' | 'zh' | 'both' }>(),
    env.DB.prepare(
      `SELECT id, day_number, title, content, language, model, prompt_hash
       FROM stories
       WHERE world_id = ? AND user_id = ?
       ORDER BY day_number ASC`,
    )
      .bind(worldId, auth.user.id)
      .all<{
        day_number: number;
        id: string;
        title: string;
        content: string;
        language: Language;
        model: string;
        prompt_hash: string;
      }>(),
    env.DB.prepare(
      `SELECT story_id, beat_index, time_slot, location, mood, event, dialogue, participating_characters, memory_impact
       FROM story_beats
       WHERE world_id = ? AND user_id = ?
       ORDER BY beat_index ASC`,
    )
      .bind(worldId, auth.user.id)
      .all<{
        story_id: string;
        beat_index: number;
        time_slot: string;
        location: string;
        mood: string;
        event: string;
        dialogue: string;
        participating_characters: string;
        memory_impact: string;
      }>(),
  ]);
  const beatsByStory = new Map<string, Array<{
    beatIndex: number;
    timeSlot: string;
    location: string;
    mood: string;
    event: string;
    dialogue: string[];
    participatingCharacters: string[];
    memoryImpact: string;
  }>>();
  for (const beat of beats.results) {
    const list = beatsByStory.get(beat.story_id) ?? [];
    list.push({
      beatIndex: beat.beat_index,
      timeSlot: beat.time_slot,
      location: beat.location,
      mood: beat.mood,
      event: beat.event,
      dialogue: parseJsonList(beat.dialogue),
      participatingCharacters: parseJsonList(beat.participating_characters),
      memoryImpact: beat.memory_impact,
    });
    beatsByStory.set(beat.story_id, list);
  }

  return {
    format: 'ai-town-lite-world',
    version: 1,
    exportedAt: new Date().toISOString(),
    source: {
      worldName: world.name,
      storyDay: world.story_day,
      language: world.language,
    },
    world: {
      name: world.name,
      language: world.language,
      storyDay: world.story_day,
    },
    characters: characters.results.map((character) => ({
      id: character.id,
      name: character.name,
      gender: character.gender,
      personality: character.personality,
      appearance: character.appearance,
      backstory: character.backstory,
      isAutoGenerated: character.is_auto_generated === 1,
    })),
    memories: memories.results.map((memory) => ({
      id: memory.id,
      characterId: memory.character_id,
      content: memory.content,
      source: memory.source,
      importance: memory.importance,
    })),
    lexiconEntries: lexiconEntries.results,
    stories: stories.results.map((story) => ({
      id: story.id,
      dayNumber: story.day_number,
      title: story.title,
      content: story.content,
      language: story.language,
      model: story.model,
      promptHash: story.prompt_hash,
      beats: beatsByStory.get(story.id) ?? [],
    })),
  };
}

export async function importWorldSnapshot(env: Env, auth: AuthContext, data: WorldExportData): Promise<string> {
  validateWorldExportData(data);

  const worldId = newId('wld');
  const characterIdMap = new Map<string, string>();
  const statements = [
    env.DB.prepare(
      `INSERT INTO worlds (id, user_id, name, language, story_day)
       VALUES (?, ?, ?, ?, ?)`,
    ).bind(worldId, auth.user.id, `${sanitizeName(data.world.name)} (Imported)`, data.world.language, data.world.storyDay),
  ];

  for (const character of data.characters) {
    const newCharacterId = newId('chr');
    characterIdMap.set(character.id, newCharacterId);
    statements.push(
      env.DB.prepare(
        `INSERT INTO characters
          (id, world_id, user_id, name, gender, personality, appearance, backstory, is_auto_generated)
         VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)`,
      ).bind(
        newCharacterId,
        worldId,
        auth.user.id,
        character.name,
        character.gender,
        character.personality,
        character.appearance,
        character.backstory,
        character.isAutoGenerated ? 1 : 0,
      ),
    );
  }

  for (const memory of data.memories) {
    statements.push(
      env.DB.prepare(
        `INSERT INTO memories (id, world_id, user_id, character_id, content, source, importance)
         VALUES (?, ?, ?, ?, ?, ?, ?)`,
      ).bind(
        newId('mem'),
        worldId,
        auth.user.id,
        memory.characterId ? (characterIdMap.get(memory.characterId) ?? null) : null,
        memory.content,
        memory.source,
        memory.importance,
      ),
    );
  }

  for (const entry of data.lexiconEntries) {
    statements.push(
      env.DB.prepare(
        `INSERT INTO lexicon_entries (id, world_id, user_id, term, description, language)
         VALUES (?, ?, ?, ?, ?, ?)`,
      ).bind(newId('lex'), worldId, auth.user.id, entry.term, entry.description, entry.language),
    );
  }

  for (const story of data.stories) {
    const storyId = newId('sty');
    statements.push(
      env.DB.prepare(
        `INSERT INTO stories (id, world_id, user_id, day_number, title, content, language, model, prompt_hash)
         VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)`,
      ).bind(
        storyId,
        worldId,
        auth.user.id,
        story.dayNumber,
        story.title,
        story.content,
        story.language,
        story.model,
        story.promptHash,
      ),
    );
    for (let i = 0; i < (story.beats ?? []).length; i += 1) {
      const beat = story.beats![i]!;
      statements.push(
        env.DB.prepare(
          `INSERT INTO story_beats
            (id, story_id, world_id, user_id, beat_index, time_slot, location, mood, event, dialogue, participating_characters, memory_impact)
           VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`,
        ).bind(
          newId('bea'),
          storyId,
          worldId,
          auth.user.id,
          i,
          beat.timeSlot,
          beat.location,
          beat.mood,
          beat.event,
          JSON.stringify(beat.dialogue),
          JSON.stringify(beat.participatingCharacters),
          beat.memoryImpact,
        ),
      );
    }
  }

  await env.DB.batch(statements);
  return worldId;
}

export async function deleteWorld(env: Env, auth: AuthContext, worldId: string): Promise<boolean> {
  const result = await env.DB.prepare(`DELETE FROM worlds WHERE id = ? AND user_id = ?`).bind(worldId, auth.user.id).run();
  return result.meta.changes > 0;
}

export async function updateWorldName(
  env: Env,
  auth: AuthContext,
  worldId: string,
  name: string,
): Promise<WorldSummary | null> {
  const result = await env.DB.prepare(
    `UPDATE worlds
     SET name = ?, updated_at = datetime('now')
     WHERE id = ? AND user_id = ?`,
  )
    .bind(sanitizeName(name), worldId, auth.user.id)
    .run();
  if (result.meta.changes === 0) return null;

  return (await listWorlds(env, auth)).find((world) => world.id === worldId) ?? null;
}

export async function updateWorldSettings(
  env: Env,
  auth: AuthContext,
  worldId: string,
  settings: { autoAdvanceEnabled?: boolean },
): Promise<WorldSummary | null> {
  const existing = await env.DB.prepare(
    `SELECT id FROM worlds WHERE id = ? AND user_id = ? LIMIT 1`,
  )
    .bind(worldId, auth.user.id)
    .first<{ id: string }>();
  if (!existing) return null;

  await env.DB.prepare(
    `UPDATE worlds
     SET auto_advance_enabled = ?, updated_at = datetime('now')
     WHERE id = ? AND user_id = ?`,
  )
    .bind(settings.autoAdvanceEnabled ? 1 : 0, worldId, auth.user.id)
    .run();

  return (await listWorlds(env, auth)).find((world) => world.id === worldId) ?? null;
}

function toWorldSummary(row: WorldRow): WorldSummary {
  return {
    id: row.id,
    name: row.name,
    language: row.language,
    storyDay: row.story_day,
    createdAt: row.created_at,
    updatedAt: row.updated_at,
    characterCount: row.character_count,
    memoryCount: row.memory_count,
    storyCount: row.story_count,
    autoAdvanceEnabled: row.auto_advance_enabled === 1,
  };
}

function sanitizeName(value: string): string {
  const trimmed = value.trim();
  if (trimmed.length === 0) return 'AI Town Lite';
  return trimmed.slice(0, 80);
}

function validateWorldExportData(data: WorldExportData): void {
  if (data.format !== 'ai-town-lite-world' || data.version !== 1) {
    throw new Error('Unsupported world export format.');
  }
  if (!data.world || !['en', 'zh'].includes(data.world.language)) {
    throw new Error('Invalid world export metadata.');
  }
  if (!Array.isArray(data.characters) || data.characters.length > 64) {
    throw new Error('Invalid character list.');
  }
  if (!Array.isArray(data.memories) || data.memories.length > 1000) {
    throw new Error('Invalid memory list.');
  }
  if (!Array.isArray(data.lexiconEntries) || data.lexiconEntries.length > 1000) {
    throw new Error('Invalid lexicon list.');
  }
  if (!Array.isArray(data.stories) || data.stories.length > 1000) {
    throw new Error('Invalid story list.');
  }
}

function parseJsonList(value: string): string[] {
  try {
    const parsed = JSON.parse(value) as unknown;
    return Array.isArray(parsed) ? parsed.filter((item): item is string => typeof item === 'string') : [];
  } catch {
    return [];
  }
}
