export type Language = 'en' | 'zh';
export type Provider = 'github' | 'google';
export type LexiconLanguage = 'en' | 'zh' | 'both';

export type Bootstrap = {
  authenticated: boolean;
  user: null | {
    id: string;
    displayName: string;
    provider: Provider;
  };
};

export type WorldSummary = {
  id: string;
  name: string;
  language: Language;
  storyDay: number;
  characterCount: number;
  memoryCount: number;
  storyCount: number;
  updatedAt: string;
  autoAdvanceEnabled: boolean;
};

export type CharacterRecord = {
  id: string;
  name: string;
  gender: string;
  personality: string;
  appearance: string;
  backstory: string;
  isAutoGenerated: boolean;
};

export type LexiconRecord = {
  id: string;
  term: string;
  description: string;
  language: LexiconLanguage;
};

export type StoryBeat = {
  beatIndex?: number;
  timeSlot: string;
  location: string;
  mood: string;
  event: string;
  dialogue: string[];
  participatingCharacters: string[];
  memoryImpact: string;
};

export type StoryRecord = {
  id?: string;
  dayNumber: number;
  title: string;
  content: string;
  language: Language;
  model: string;
  createdAt: string;
  beats: StoryBeat[];
};

export type WorldContent = {
  characters: CharacterRecord[];
  lexiconEntries: LexiconRecord[];
  stories: StoryRecord[];
};

export type MapPlace = {
  key: string;
  label: string;
  labelZh: string;
  x: number;
  y: number;
  aliases: string[];
};
